name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Generate A.bam
      id: generate-a-bam
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Generate A.bam
        setup-command: "conda env update -q -f environment.yaml"
        command: conda run -n snakemake-tutorial snakemake --cores 1 mapped_reads/A.bam
        timeout: 10
        max-score: 2
    - name: Dry run of A.bam
      id: dry-run-of-a-bam
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Dry run of A.bam
        setup-command: "conda env update -q -f environment.yaml"
        command: conda run -n snakemake-tutorial snakemake -np mapped_reads/A.bam
        timeout: 10
        max-score: 2
    # FIXME Everyone needs two lines in-between rules
    # - name: Check snakemakefmt
    #   id: check-snakemakefmt
    #   uses: classroom-resources/autograding-command-grader@v1
    #   with:
    #     test-name: Check snakemakefmt
    #     setup-command: "conda env update -q -f environment.yaml"
    #     command: conda run -n snakemake-tutorial snakefmt --check
    #     timeout: 10
    #     max-score: 2
    - name: Dry run passes
      id: dry-run
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Dry run passes
        setup-command: "conda env update -q -f environment.yaml"
        command: conda run -n snakemake-tutorial snakemake -n
        timeout: 10
        max-score: 2
    - name: Full Workflow
      id: full-workflow
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Full Workflow
        setup-command: "conda env update -q -f environment.yaml"
        command: conda run -n snakemake-tutorial snakemake --cores 2
        timeout: 10
        max-score: 2
    - name: Run Tests
      id: run-tests
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Run Tests
        setup-command: "conda env update -q -f environment.yaml"
        command: conda run -n snakemake-tutorial pytest
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        GENERATE-A-BAM_RESULTS: "${{steps.generate-a-bam.outputs.result}}"
        DRY-RUN-OF-A-BAM_RESULTS: "${{steps.dry-run-of-a-bam.outputs.result}}"
        CHECK-SNAKEMAKEFMT_RESULTS: "${{steps.check-snakemakefmt.outputs.result}}"
        DRY-RUN_RESULTS: "${{steps.dry-run.outputs.result}}"
        FULL-WORKFLOW_RESULTS: "${{steps.full-workflow.outputs.result}}"
        RUN-TESTS_RESULTS: "${{steps.run-tests.outputs.result}}"
      with:
        runners: generate-a-bam,dry-run-of-a-bam,dry-run,full-workflow,run-tests
